[package]
name = "rs-music-bot"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15.7"
poise = "0.6.1"
serenity = "0.12.5"
songbird = "0.5.0"
tokio = "1.49.0"
tracing = "0.1.44"
yt-dlp = "1.4.7"
